name: CI

on:
  push:
    # Avoid duplicate builds on PRs.
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  # Used by shfmt and more.
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.4"
      - name: Run ShellCheck
        run: make lint-scripts
      - name: Run shfmt
        uses: docker://mvdan/shfmt:latest
        with:
          args: "--diff ."
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: false
      - name: Run Ruff check
        run: uvx ruff check --output-format=github
      - name: Run Ruff format
        run: uvx ruff format --diff

  integration-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        stack: ["heroku-22", "heroku-24"]
    env:
      HATCHET_APP_LIMIT: 300
      HATCHET_DEFAULT_STACK: ${{ matrix.stack }}
      HATCHET_EXPENSIVE_MODE: 1
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_API_USER: ${{ secrets.HEROKU_API_USER }}
      HEROKU_DISABLE_AUTOUPDATE: 1
      PARALLEL_SPLIT_TEST_PROCESSES: 20
      RSPEC_RETRY_RETRY_COUNT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.4"
      - name: Hatchet setup
        run: bundle exec hatchet ci:setup
      - name: Run Hatchet integration tests
        # parallel_split_test runs rspec in parallel, with concurrency equal to PARALLEL_SPLIT_TEST_PROCESSES.
        run: bundle exec parallel_split_test spec/hatchet/

  container-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run Python unit tests
        run: make run-python-tests
      - name: Run buildpack using default app fixture
        run: make run
